import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

// Verify the network security config file ships with the project and that
// its structure is what Android expects. This file is generated by
// `expo prebuild` — if it doesn't exist, it means prebuild hasn't been
// run yet (e.g. in a fresh checkout). In that case, skip the tests rather
// than failing CI on unrelated changes.

const here = dirname(fileURLToPath(import.meta.url));
const mobileRoot = join(here, '..', '..');

describe('Android network_security_config', () => {
  const path = join(
    mobileRoot,
    'android',
    'app',
    'src',
    'main',
    'res',
    'xml',
    'network_security_config.xml',
  );

  const fileExists = existsSync(path);

  it('exists at the expected path', () => {
    if (!fileExists) return; // skip if prebuild hasn't been run
    expect(fileExists).toBe(true);
  });

  it('disables cleartext traffic globally', () => {
    if (!fileExists) return;
    const xml = readFileSync(path, 'utf8');
    expect(xml).toMatch(/cleartextTrafficPermitted="false"/);
  });

  it('pins the supabase.co domain', () => {
    if (!fileExists) return;
    const xml = readFileSync(path, 'utf8');
    expect(xml).toMatch(/<domain[^>]*>supabase\.co<\/domain>/);
  });

  it('declares at least two pins (leaf + backup)', () => {
    if (!fileExists) return;
    const xml = readFileSync(path, 'utf8');
    const pinCount = (xml.match(/<pin digest="SHA-256">/g) ?? []).length;
    expect(pinCount).toBeGreaterThanOrEqual(2);
  });

  it('uses SHA-256 digests (not SHA-1)', () => {
    if (!fileExists) return;
    const xml = readFileSync(path, 'utf8');
    expect(xml).not.toMatch(/<pin digest="SHA-1">/);
  });

  it('references the config from app.json', () => {
    const appJson = JSON.parse(readFileSync(join(mobileRoot, 'app.json'), 'utf8'));
    expect(appJson.expo.android.networkSecurityConfig).toMatch(
      /network_security_config\.xml$/,
    );
  });
});
