/**
 * M3.4 — the mobile clinical command adapter.
 *
 * The client never chooses a clinical status and never reaches into
 * `approval_requests`. Every write goes through `submit_case_operation` (the
 * same RPC the durable queue flushes, so the online and offline paths behave
 * identically), and every transition into the review queue goes through
 * `submit_case_command`, which creates the approval requests, the audit row and
 * the outbox row in one transaction.
 *
 * Two rules the boundary depends on:
 *
 *  1. A resident content edit may only land on `draft` or `rejected`. `pending`
 *     is the command's transition and `approved` is the decide command's, so an
 *     edit payload naming either is an approval request the client is not
 *     entitled to make. A `rejected` row is normalised back to `draft` first,
 *     which is the documented resident hop.
 *  2. A retry of the same resubmission replays the same request id. The command
 *     is keyed by (tenant, actor, command, request_id), so a retried tap returns
 *     the stored result instead of opening a second approval round. A genuinely
 *     new attempt mints a fresh id, which is what `newCaseCommandRequestId` is
 *     for; the adapter never mints one on its own.
 *
 * Outcomes are honest. `queued-locally` means the content is on this device and
 * nothing was sent; the caller must not describe it as submitted.
 */

import { canPerform, type SensitiveAction } from './authorization';
import { classifyQueueError } from './durable-queue';
import { logInfo, logWarn } from './logger';
import { submitCase, type SubmitOutcome } from './case-submit';
import { buildCaseContent, withPatientHash, type CaseContentInput } from './case-payload';
import type { CapabilitySnapshot } from './capability';

export type CaseCommandOutcome =
  | { kind: 'submitted'; caseId: string }
  | { kind: 'draft-saved'; caseId: string; code: string }
  | { kind: 'queued-locally'; opId: string }
  | { kind: 'rejected'; reason: string };

export interface CaseCommandResult {
  success?: boolean;
  case_id?: string;
  id?: string;
  code?: string;
  error?: string;
}

export interface CaseCommandDeps {
  /**
   * The one snapshot every step is gated on. The screen resolves it per
   * attempt; a null snapshot fails closed before any write.
   */
  capability: CapabilitySnapshot | null;
  /** The durable submit adapter: online write, offline queue, capability gate. */
  submit: (input: {
    action: 'insert' | 'update';
    targetId?: string;
    payload: Record<string, unknown>;
  }) => Promise<SubmitOutcome>;
  /** submit_case_command over the authenticated session. */
  submitCommand: (args: {
    caseId: string;
    requestId: string;
    expectedStatus: string;
  }) => Promise<{ data: CaseCommandResult | null; error: { message: string } | null }>;
}

/** Columns the durable queue and the operation RPC both refuse as client input. */
const SERVER_OWNED_COLUMNS = ['id', 'tenant_id', 'resident_id', 'client_operation_id', 'local_scope'] as const;

type OperationRpcResult = { success?: boolean; id?: string; error?: string; code?: string };

type OperationRpc = (
  fn: 'submit_case_operation',
  args: {
    p_op_id: string;
    p_action: 'insert' | 'update' | 'delete';
    p_row_id: string | null;
    p_payload: Record<string, unknown>;
  },
) => Promise<{ data: OperationRpcResult | null; error: { message: string } | null }>;

/**
 * One request id per resubmission attempt.
 *
 * Generated by the caller, never by the adapter, so the identity of "the same
 * attempt" is the caller's to hold across retries.
 */
export function newCaseCommandRequestId(): string {
  const bytes = new Uint8Array(16);
  const webcrypto = (globalThis as { crypto?: Crypto }).crypto;
  if (!webcrypto || typeof webcrypto.getRandomValues !== 'function') {
    throw new Error('policy: no secure random source');
  }
  webcrypto.getRandomValues(bytes);
  bytes[6] = (bytes[6] & 0x0f) | 0x40;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

function operationPayload(payload: Record<string, unknown>): {
  opId: string;
  body: Record<string, unknown>;
} {
  const opId = typeof payload.client_operation_id === 'string' ? payload.client_operation_id : newCaseCommandRequestId();
  const body: Record<string, unknown> = { ...payload };
  for (const column of SERVER_OWNED_COLUMNS) delete body[column];
  return { opId, body };
}

/**
 * Bind the durable submit adapter to the operation RPC.
 *
 * `submitCase` owns the capability gate, the de-identification mode match, the
 * offline queue and the op id; this only supplies the wire format, and it
 * reports the RPC's own refusal by throwing so `submitCase` classifies it
 * instead of claiming a write that did not happen.
 */
export function createCaseOperationSubmit(
  client: { rpc: OperationRpc },
  capability: CapabilitySnapshot | null,
): CaseCommandDeps['submit'] {
  const { rpc } = client;
  return async (input) =>
    submitCase(
      {
        capability,
        insertRow: async (payload) => {
          const { opId, body } = operationPayload(payload);
          const res = await rpc('submit_case_operation', {
            p_op_id: opId,
            p_action: 'insert',
            p_row_id: null,
            p_payload: body,
          });
          if (res.error) throw new Error(res.error.message);
          if (!res.data?.success) throw new Error(res.data?.error ?? 'the case draft was refused');
          return { serverId: res.data.id ?? null };
        },
        updateRow: async (targetId, payload) => {
          const { opId, body } = operationPayload(payload);
          const res = await rpc('submit_case_operation', {
            p_op_id: opId,
            p_action: 'update',
            p_row_id: targetId,
            p_payload: body,
          });
          if (res.error) throw new Error(res.error.message);
          if (!res.data?.success) throw new Error(res.data?.error ?? 'the case edit was refused');
          return { serverId: res.data.id ?? null };
        },
      },
      { action: input.action, targetId: input.targetId, payload: input.payload },
    );
}

function gateOutcome(action: SensitiveAction, capability: CapabilitySnapshot | null): CaseCommandOutcome | null {
  const gate = canPerform(capability, action);
  if (gate.ok) return null;
  logWarn('clinical-commands.denied', { action, reason: gate.reason ?? 'denied' });
  return { kind: 'rejected', reason: gate.reason ?? 'not permitted' };
}

/** The command is a network call like any other: a refusal is still a refusal. */
async function runSubmitCommand(
  deps: CaseCommandDeps,
  caseId: string,
  requestId: string,
): Promise<CaseCommandOutcome> {
  let response: { data: CaseCommandResult | null; error: { message: string } | null };
  try {
    response = await deps.submitCommand({ caseId, requestId, expectedStatus: 'draft' });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logWarn('clinical-commands.transient', { errorClass: classifyQueueError(msg) });
    return { kind: 'rejected', reason: msg };
  }
  if (response.error) {
    const msg = response.error.message;
    logWarn('clinical-commands.command-error', { errorClass: classifyQueueError(msg) });
    return { kind: 'rejected', reason: msg };
  }
  const body = response.data;
  if (body?.success === true) {
    logInfo('clinical-commands.submitted', { command: 'submit_case' });
    return { kind: 'submitted', caseId: body.case_id ?? caseId };
  }
  // The draft exists and stays a draft. A tenant with no eligible reviewer is
  // not an error the resident caused, so the code is handed back for copy.
  const code = body?.code ?? 'submit_failed';
  logWarn('clinical-commands.draft-only', { code });
  return { kind: 'draft-saved', caseId, code };
}

export interface EditCaseInput {
  caseId: string;
  /** The status the server reported for the row being edited. */
  status: 'draft' | 'rejected';
  content: CaseContentInput;
  requestId: string;
}

/**
 * Edit a draft or rejected case, then send it for review.
 *
 * The write carries `status: 'draft'` and the content columns only. For a
 * rejected row that is the resident hop the write-once guard allows; the
 * command then owns `draft -> pending` and writes the approval requests.
 */
export async function editCaseAndResubmit(
  deps: CaseCommandDeps,
  input: EditCaseInput,
): Promise<CaseCommandOutcome> {
  const capability = deps.capability;
  const denied = gateOutcome('case:edit', capability);
  if (denied) return denied;

  const written = await deps.submit({
    action: 'update',
    targetId: input.caseId,
    payload: { ...buildCaseContent(input.content), status: 'draft' },
  });

  if (written.kind === 'rejected') return written;
  if (written.kind === 'queued-locally') {
    // The content is on this device and the command cannot run without the row
    // it would move. Reporting anything stronger would claim a review round
    // that has not been requested.
    logInfo('clinical-commands.queued-locally', { action: 'edit', from: input.status });
    return written;
  }

  return runSubmitCommand(deps, input.caseId, input.requestId);
}

export interface CreateCaseInput {
  content: CaseContentInput;
  requestId: string;
}

/** Create a draft, then send it for review. Never writes a status of its own. */
export async function createCaseDraftAndSubmit(
  deps: CaseCommandDeps,
  input: CreateCaseInput,
): Promise<CaseCommandOutcome> {
  const capability = deps.capability;
  const denied = gateOutcome('case:create', capability);
  if (denied) return denied;

  const written = await deps.submit({
    action: 'insert',
    payload: {
      ...withPatientHash(buildCaseContent(input.content), input.content.patientHash),
      status: 'draft',
    },
  });

  if (written.kind !== 'submitted') return written;
  const caseId = written.serverId;
  if (!caseId) return { kind: 'rejected', reason: 'the server did not return a case id' };

  return runSubmitCommand(deps, caseId, input.requestId);
}
