import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 3,
  tables: [
    tableSchema({
      name: 'case_entries',
      columns: [
        { name: 'tenant_id', type: 'string' },
        { name: 'resident_id', type: 'string' },
        { name: 'template_id', type: 'string' },
        { name: 'patient_mrn', type: 'string', isOptional: true },
        { name: 'patient_dob', type: 'string', isOptional: true },
        { name: 'patient_age_years', type: 'number', isOptional: true },
        { name: 'patient_hash', type: 'string', isOptional: true },
        { name: 'case_date', type: 'string' },
        { name: 'field_values', type: 'string' },
        { name: 'accreditation_mappings', type: 'string' },
        { name: 'is_deidentified', type: 'boolean' },
        { name: 'status', type: 'string' },
        { name: 'local_sync_status', type: 'string' },
        { name: 'server_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'case_templates',
      columns: [
        { name: 'tenant_id', type: 'string' },
        { name: 'specialty', type: 'string' },
        { name: 'name', type: 'string' },
        { name: 'fields', type: 'string' },
        { name: 'required_fields', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'program_goals',
      columns: [
        { name: 'tenant_id', type: 'string' },
        { name: 'resident_id', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'target_count', type: 'number' },
        { name: 'current_count', type: 'number' },
        { name: 'specialty', type: 'string', isOptional: true },
        { name: 'local_sync_status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'rotations',
      columns: [
        { name: 'tenant_id', type: 'string' },
        { name: 'resident_id', type: 'string' },
        { name: 'title', type: 'string' },
        { name: 'specialty', type: 'string', isOptional: true },
        { name: 'start_date', type: 'string' },
        { name: 'end_date', type: 'string' },
        { name: 'site', type: 'string', isOptional: true },
        { name: 'supervisor_id', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'notes', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'milestones',
      columns: [
        { name: 'tenant_id', type: 'string' },
        { name: 'resident_id', type: 'string' },
        { name: 'competency_area', type: 'string' },
        { name: 'sub_competency', type: 'string' },
        { name: 'level', type: 'number' },
        { name: 'assessor_id', type: 'string', isOptional: true },
        { name: 'assessment_date', type: 'string' },
        { name: 'evidence_entry_id', type: 'string', isOptional: true },
        { name: 'comments', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'evaluation_forms',
      columns: [
        { name: 'tenant_id', type: 'string' },
        { name: 'resident_id', type: 'string' },
        { name: 'evaluator_id', type: 'string' },
        { name: 'form_type', type: 'string' },
        { name: 'encounter_date', type: 'string', isOptional: true },
        { name: 'setting', type: 'string', isOptional: true },
        { name: 'patient_context', type: 'string', isOptional: true },
        { name: 'ratings', type: 'string' },
        { name: 'overall_score', type: 'number', isOptional: true },
        { name: 'feedback', type: 'string', isOptional: true },
        { name: 'action_plan', type: 'string', isOptional: true },
        { name: 'status', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'comments',
      columns: [
        { name: 'tenant_id', type: 'string' },
        { name: 'entry_id', type: 'string', isOptional: true },
        { name: 'evaluation_id', type: 'string', isOptional: true },
        { name: 'author_id', type: 'string' },
        { name: 'body', type: 'string' },
        { name: 'parent_id', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
  ],
});
