import { authenticate, corsHeaders, escapeHtml } from '../_shared/auth.ts';

interface CaseData {
  case_date: string;
  patient_mrn?: string;
  specialty: string;
  name: string;
}

interface GeneratePdfPayload {
  cases: CaseData[];
  resident_name: string;
  tenant: string;
}

Deno.serve(async (req: Request) => {
  const origin = req.headers.get('Origin');
  const headers = corsHeaders(origin);

  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers });
  }

  const authResult = await authenticate(req);
  if (authResult instanceof Response) return authResult;

  let payload: GeneratePdfPayload;
  try {
    payload = await req.json();
  } catch {
    return new Response(
      JSON.stringify({ error: 'Invalid JSON body' }),
      { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
    );
  }

  const { cases, resident_name, tenant } = payload;

  if (!cases || !Array.isArray(cases) || !resident_name || !tenant) {
    return new Response(
      JSON.stringify({ error: 'Missing required fields: cases, resident_name, tenant' }),
      { status: 400, headers: { ...headers, 'Content-Type': 'application/json' } }
    );
  }

  const now = new Date().toLocaleString('en-US', { timeZone: 'UTC' });

  const rows = cases
    .map(
      (c) => `
      <tr>
        <td style="padding:8px;border:1px solid #ddd">${escapeHtml(c.case_date)}</td>
        <td style="padding:8px;border:1px solid #ddd">${escapeHtml(c.specialty)} - ${escapeHtml(c.name)}</td>
      </tr>`
    )
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>E-Logbook Case Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    .header { text-align: center; margin-bottom: 30px; }
    .header h1 { margin: 0; font-size: 24px; }
    .header p { margin: 4px 0; color: #666; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
    th { background: #f5f5f5; padding: 10px 8px; border: 1px solid #ddd; text-align: left; font-size: 13px; }
    td { font-size: 13px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; text-align: center; }
    .footer p { margin: 4px 0; }
  </style>
</head>
<body>
  <div class="header">
    <h1>E-Logbook Case Report</h1>
    <p>Resident: ${escapeHtml(resident_name)}</p>
    <p>Tenant: ${escapeHtml(tenant)}</p>
    <p>Generated: ${escapeHtml(now)}</p>
  </div>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Template</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>

  <div class="footer">
    <p>This report was self-attested by the resident. Verify all entries before submission.</p>
    <p>Generated by E-Logbook on ${escapeHtml(now)}</p>
  </div>
</body>
</html>`;

  return new Response(html, {
    headers: { ...headers, 'Content-Type': 'text/html' },
  });
});