interface CaseData {
  case_date: string;
  patient_mrn: string;
  specialty: string;
  name: string;
}

interface GeneratePdfPayload {
  cases: CaseData[];
  resident_name: string;
  tenant: string;
}

Deno.serve(async (req: Request) => {
  const payload: GeneratePdfPayload = await req.json();
  const { cases, resident_name, tenant } = payload;

  const now = new Date().toLocaleString('en-US', { timeZone: 'UTC' });

  const rows = cases
    .map(
      (c) => `
      <tr>
        <td style="padding:8px;border:1px solid #ddd">${c.case_date}</td>
        <td style="padding:8px;border:1px solid #ddd">${c.specialty} - ${c.name}</td>
        <td style="padding:8px;border:1px solid #ddd">${c.patient_mrn}</td>
      </tr>`
    )
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>E-Logbook Case Report</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    .header { text-align: center; margin-bottom: 30px; }
    .header h1 { margin: 0; font-size: 24px; }
    .header p { margin: 4px 0; color: #666; font-size: 14px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
    th { background: #f5f5f5; padding: 10px 8px; border: 1px solid #ddd; text-align: left; font-size: 13px; }
    td { font-size: 13px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; text-align: center; }
    .footer p { margin: 4px 0; }
  </style>
</head>
<body>
  <div class="header">
    <h1>E-Logbook Case Report</h1>
    <p>Resident: ${resident_name}</p>
    <p>Tenant: ${tenant}</p>
    <p>Generated: ${now}</p>
  </div>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Template</th>
        <th>MRN</th>
      </tr>
    </thead>
    <tbody>
      ${rows}
    </tbody>
  </table>

  <div class="footer">
    <p>This report was self-attested by the resident. Verify all entries before submission.</p>
    <p>Generated by E-Logbook on ${now}</p>
  </div>
</body>
</html>`;

  return new Response(html, {
    headers: { 'Content-Type': 'text/html' },
  });
});
